name: import Neubias biii.eu content

on:
  workflow_dispatch:

jobs:

  build-biii-raw-bioschemas:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: content
    - uses: actions/checkout@v2
      with:
        repository: bio-agents/content-ecosystem-utils
        path: content-ecosystem-utils
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.7"
    - name: Install dependencies
      run:
        pip install -r ${{ github.workspace }}/content-ecosystem-utils/scripts/neubias/requirements.txt
    - name: dump Neubias biii.eu data as bioschemas and raw files
      run: |
        cd ${{ github.workspace }}/content/data
        if ${{ github.workspace }}/content-ecosystem-utils/scripts/git-utils/checkout-pr-if-exist.sh biii-import; then
          IS_PR_CREATED=true
        else
          IS_PR_CREATED=false
        fi

        cd ${{ github.workspace }}/content-ecosystem-utils/scripts/neubias
        python biseEU_LD_export.py -td http://biii.eu -dump

        echo "IS_PR_CREATED=$IS_PR_CREATED" >> $GITHUB_ENV

    - name: commit new data and push to PR
      env:
        GITHUB_USER: ${{ secrets.GITHUB_USER }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd ${{ github.workspace }}/content/data
        ${{ github.workspace }}/content-ecosystem-utils/scripts/git-utils/import-changes.sh $IS_PR_CREATED biii-import
