name: dump bio.agents data in a single bioschemas file

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 0'
    
jobs:
  build-bioschemas:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: content

      - uses: actions/checkout@v2
        with:
          repository: bio-agents/content-ecosystem-utils
          path: content-ecosystem-utils

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - name: Install dependencies
        run: pip install -r ${{ github.workspace }}/content-ecosystem-utils/scripts/bioschemas/requirements.txt

      - name: dump bio.agents data in a single bioschemas file
        run: |
          cd ${{ github.workspace }}/content-ecosystem-utils/scripts/bioschemas
          python bioschemas_dump.py
          mv ${{ github.workspace }}/content-ecosystem-utils/scripts/bioschemas/bioschemas-dump.ttl ${{ github.workspace }}/content/datasets/

      - name: commit new data
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ${{ github.workspace }}/content/
          git config --local user.email "tpe-bot@github.com"
          git config --local user.name "Agents Platform Ecosystem bot"
          git add .
          if git commit -m "build bioschemas RDF dump on $(date)"; then
              git push origin HEAD
              echo "successfully created new data"
          else
              echo "nothing new to add, exiting"            
          fi
