name: import debian-med contents

on: 
  workflow_dispatch:
  
jobs:
  import-debianmed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: checkout bioagentsConnect
      uses: actions/checkout@v2
      with:
        # Repository name with owner. For example, actions/checkout
        # Default: ${{ github.repository }}
        repository: 'bio-agents/bioagentsConnect'
        path: bioagentsConnect
    - name: install pgsql client
      run: |
        sudo apt-get install postgresql-client
    - name: install pyyaml
      working-directory: bioagentsConnect
      run: |
        cd DebianMed
        pip3 install -r requirements.txt
    - name: run script
      working-directory: bioagentsConnect
      run: |
        cd DebianMed
        python query_deb.py ../../data
        cd ../../data
        git status
    - name: commit new data and push to new PR
      env:
        GITHUB_USER: ${{ secrets.GITHUB_USER }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "tpe-bot@github.com"
        git config --local user.name "Agents Platform Ecosystem bot"
        cd data
        git add .
        if git commit -m "import from Debian Med on $(date)"; then
          git checkout -b debianmed_import_${{ github.run_id }}
          git push --set-upstream origin "debianmed_import_${{ github.run_id }}"
          hub pull-request -m "import from Debian Med on $(date)"
          echo "successfully created new data"
        else
          echo "nothing new to add, exiting"
        fi
